### ISSUE TITLE
Python 2.7 compatibility problem

### ISSUE THREAD

**Issue by dertuncay** [arkottke/pyrotd#1]
__init__.py at /usr/lib/python2.7/site-packages/pyrotd/ is not compatible with python 2.7. 

What kind of changes should be done?

**Comment by arkottke** [comment]
The changes required should be relatively minor. Did you want to attempt to
make the changes or do you want me to do that?

On Jun 15, 2017 3:44 AM, "Deniz" <notifications@github.com> wrote:

*init*.py at /usr/lib/python2.7/site-packages/pyrotd/ is not compatible
with python 2.7.

What kind of changes should be done?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arkottke/pyrotd/issues/1>, or mute the thread

**Comment by dertuncay** [comment]
I can do the changes, If you provide the parts that need modifications.

2017-06-15 15:50 GMT+02:00 Albert Kottke <notifications@github.com>:

> The changes required should be relatively minor. Did you want to attempt to
> make the changes or do you want me to do that?
>

**Comment by arkottke** [comment]
I wasn't sure what was required so I went ahead and addressed the issues. You should be able to install v0.5.0 from PyPi.
